/*
 * VMC Migration Hub - VMware Docs Article Search API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"net/http"
)

func AdvancedSearchPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	a1 := &Article{
		Highlight: &ArticleHighlight{
			Title: "test",
			Content: []string {"a", "b"},
		},
		Score: 3342323233,
		Source: &ArticleSource{
			Title: "test",
			CContents: []string{"a", "aa"},
			LastModified: "2010-12-21 10:00:00 PM",
			PublicationUrl: "https://dd.dd",
			Url: "https://dd.dd",
		},
	}

	b, err := json.Marshal(a1)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	w.WriteHeader(http.StatusOK)
	w.Write(b)
}
