/*
 * VMC Migration Hub - VMware Docs Article Search API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArticleSearchResponse struct {

	Topics []Article `json:"topics,omitempty"`

	Status string `json:"status,omitempty"`

	Total float32 `json:"total,omitempty"`
}
