/*
 * VMC Migration Hub - VMware Docs Article Search API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArticleSource struct {

	CContents []string `json:"c-contents,omitempty"`

	LastModified string `json:"last-modified,omitempty"`

	PublicationUrl string `json:"publication-url,omitempty"`

	Title string `json:"title,omitempty"`

	Url string `json:"url,omitempty"`
}
