/*
 * VMC Migration Hub - VMware Docs Article Search API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArticleSearchRequest struct {

	ContentSource []string `json:"contentSource,omitempty"`

	EmailId string `json:"emailId,omitempty"`

	Format string `json:"format,omitempty"`

	From string `json:"from,omitempty"`

	FromDate string `json:"fromDate,omitempty"`

	InformationType []string `json:"informationType,omitempty"`

	IsDocsApp bool `json:"isDocsApp,omitempty"`

	Language string `json:"language,omitempty"`

	ProductDoc bool `json:"productDoc,omitempty"`

	Products []string `json:"products,omitempty"`

	PublicationMd5 []string `json:"publicationMd5,omitempty"`

	QueryString *ArticleSearchRequestQueryString `json:"queryString,omitempty"`

	SaveSearchIndex bool `json:"saveSearchIndex,omitempty"`

	SearchType string `json:"searchType,omitempty"`

	Size string `json:"size,omitempty"`

	SortField string `json:"sortField,omitempty"`

	SortFieldType string `json:"sortFieldType,omitempty"`

	Target string `json:"target,omitempty"`

	ToDate string `json:"toDate,omitempty"`
}
