/*
 * VMC Migration Hub - VMware Docs Article Search API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Article struct {

	Highlight *ArticleHighlight `json:"highlight,omitempty"`

	Score float32 `json:"score,omitempty"`

	Source *ArticleSource `json:"source,omitempty"`
}
